# Generated by Django 5.1.7 on 2025-04-03 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chats", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="chat",
            name="username",
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
