# Generated by Django 5.1.7 on 2025-03-17 21:19

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                ("user_id", models.AutoField(primary_key=True, serialize=False)),
                ("username", models.CharField(max_length=150, unique=True)),
                (
                    "discriminator",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("password_hash", models.CharField(max_length=128)),
                ("avatar_url", models.URLField(blank=True, null=True)),
                ("bio", models.TextField(blank=True, null=True)),
                ("status", models.CharField(default="offline", max_length=30)),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("user", "User"),
                            ("mod", "Moderator"),
                            ("admin", "Admin"),
                        ],
                        default="user",
                        max_length=10,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("last_login", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "users",
            },
        ),
    ]
